package com.zwrx.bmw.models;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.GenericGenerator;
import com.zwrx.bmw.common.CommonConst;
import com.zwrx.bmw.service.BaseService;
import com.zwrx.bmw.util.BeansFactory;
import com.zwrx.bmw.util.StringUtil;

/**
 * NgbSyscode generated by hbm2java
 */
@Entity
@Table(name = "bmw_syscode")
public class BwmSyscode implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String syscodeId;		//数据字典ID
	private String type;			//类型
	private String class_;			//级别 
	private String fatherdict;		//上级字典
	private String name;			//名称
	private String sdesc;			//描述
	private String sign;			//标识
	private String state;			//状态
	private String content;			//内容

	public BwmSyscode() {
	}

	public BwmSyscode(String syscodeId) {
		this.syscodeId = syscodeId;
	}

	public BwmSyscode(String syscodeId, String type, String class_,
			String fatherdict, String name, String sdesc, String sign,
			String state, String content) {
		this.syscodeId = syscodeId;
		this.type = type;
		this.class_ = class_;
		this.fatherdict = fatherdict;
		this.name = name;
		this.sdesc = sdesc;
		this.sign = sign;
		this.state = state;
		this.content = content;
	}

	@Id
	@Column(name = "syscode_id", unique = true, nullable = false, length = 32)
	@GenericGenerator(name="idGenerator", strategy="uuid")
	@GeneratedValue(generator="idGenerator")
	public String getSyscodeId() {
		return this.syscodeId;
	}

	public void setSyscodeId(String syscodeId) {
		this.syscodeId = syscodeId;
	}

	@Column(name = "type", length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "class", length = 2)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "fatherdict", length = 32)
	public String getFatherdict() {
		return this.fatherdict;
	}

	public void setFatherdict(String fatherdict) {
		this.fatherdict = fatherdict;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sdesc", length = 400)
	public String getSdesc() {
		return this.sdesc;
	}

	public void setSdesc(String sdesc) {
		this.sdesc = sdesc;
	}

	@Column(name = "sign", length = 50)
	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	@Transient
	public List<BwmSyscode> getSubCodes(){
		BaseService baseService = (BaseService)BeansFactory.get("baseService");
		BwmSyscode syscode = new BwmSyscode();
		syscode.setState(CommonConst.STATE_NORMAL);
		syscode.setType(CommonConst.SYSCODE_TYPE_GOOD_TYPE);
		syscode.setFatherdict(this.getSyscodeId());
		syscode.setClass_(CommonConst.SYSCODE_CLASS_SECONDDARY);
		return baseService.findByExample(syscode);
	}
	
	@Transient
	public BwmSyscode getFatherCode(){
		BaseService baseService = (BaseService)BeansFactory.get("baseService");
		if(!StringUtil.isBlank(this.getFatherdict()))
			return  (BwmSyscode)baseService.findById(BwmSyscode.class, this.getFatherdict());
		return null;
	}

}
